# Generated by Django 5.2.7 on 2025-10-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='duration',
            field=models.FloatField(blank=True, help_text='Estimated travel time in minutes (ORS)', null=True),
        ),
    ]
